module:
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  external_data_source: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  image: 0
  link: 0
  link_attributes: 0
  media: 0
  media_library: 0
  menu_ui: 0
  metatag: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  search: 0
  search_api: 0
  search_api_db: 0
  shortcut: 0
  system: 0
  tablefield: 0
  tablefield_required: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_field_value: 0
  twig_tweak: 0
  umd_schoolwide_header: 0
  umd_terp_base: 0
  umd_terp_content_types: 0
  update: 0
  user: 0
  ut_accordion: 0
  ut_blockquote: 0
  ut_button: 0
  ut_card: 0
  ut_carousel: 0
  ut_divider: 0
  ut_events: 0
  ut_feature: 0
  ut_images: 0
  ut_news: 0
  ut_people: 0
  ut_sidebar_menu: 0
  ut_slideshow: 0
  ut_stats: 0
  ut_table: 0
  ut_tabs: 0
  ut_text: 0
  ut_video: 0
  ut_view: 0
  ut_webform: 0
  views_ui: 0
  viewsreference: 0
  webform: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  umd_terp: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
